// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
// To regenerate: cargo run -p kreuzberg-e2e-generator -- generate --lang wasm-deno

// Tests for image fixtures. Run with: deno test --allow-read

import type { ExtractionResult } from "./helpers.ts";
import {
	assertions,
	buildConfig,
	enableOcr,
	extractBytes,
	initWasm,
	resolveDocument,
	shouldSkipFixture,
} from "./helpers.ts";

// Initialize WASM module and enable OCR once at module load time
await initWasm();
await enableOcr();

Deno.test("image_metadata_only", { permissions: { read: true, net: true } }, async () => {
	const config = buildConfig({ ocr: null });
	let result: ExtractionResult | null = null;
	try {
		const documentBytes = await resolveDocument("images/example.jpg");
		// Sync file extraction - WASM uses extractBytes with pre-read bytes
		result = await extractBytes(documentBytes, "image/jpeg", config);
	} catch (error) {
		if (shouldSkipFixture(error, "image_metadata_only", [], undefined)) {
			return;
		}
		throw error;
	}
	if (result === null) {
		return;
	}
	assertions.assertExpectedMime(result, ["image/jpeg"]);
	assertions.assertMaxContentLength(result, 100);
});

Deno.test("image_svg_basic", { permissions: { read: true, net: true } }, async () => {
	const config = buildConfig(undefined);
	let result: ExtractionResult | null = null;
	try {
		const documentBytes = await resolveDocument("xml/simple_svg.svg");
		// Sync file extraction - WASM uses extractBytes with pre-read bytes
		result = await extractBytes(documentBytes, "image/svg+xml", config);
	} catch (error) {
		if (shouldSkipFixture(error, "image_svg_basic", [], undefined)) {
			return;
		}
		throw error;
	}
	if (result === null) {
		return;
	}
	assertions.assertExpectedMime(result, ["image/svg+xml"]);
	assertions.assertMinContentLength(result, 5);
});
